### ISSUE TITLE
Unable to disable accessories (local)

### ISSUE THREAD

**Issue by SubZane** [johnlemonse/homebridge-telldus#64]
I'm trying to disable 4 accessories that I don't want to send to homebridge, but it doesn't work. I get no errors, but the accessories show up anyway.

What have I missed?
`
{
        "bridge": {
                "username": "CD:22:3D:E3:CE:93",
                "name": "Telldus",
                "pin": "123-45-678",
                "port": 51826
        },
        "platforms": [{
                "platform": "Telldus",
                "name": "Telldus Liv!e",
                "accessories": [
                {
                        "local_id": 2,
                        "model": "temperaturehumidity",
                        "disabled": true
                },
                {
                        "local_id": 3,
                        "model": "temperaturehumidity",
                        "disabled": true
                },
                {
                        "local_id": 4,
                        "model": "temperaturehumidity",
                        "disabled": true
                },
                {
                        "local_id": 10,
                        "model": "temperaturehumidity",
                        "disabled": true
                }
                ],
                "unknown_accessories": [{
                                "local_id": 13,
                                "model": "selflearning-switch",
                                "type": "device",
                                "manufacturer": "Telldus"
                        },
                        {
                                "local_id": 14,
                                "model": "selflearning-switch",
                                "type": "device",
                                "manufacturer": "Telldus"
                        },
                        {
                                "local_id": 15,
                                "model": "selflearning-switch",
                                "type": "device",
                                "manufacturer": "Telldus"
                        }
                ],
                "local": {
                        "ip_address": "192.168.0.105",
                        "access_token": "xxx"
                }
        }]
}
`

**Comment by dezral** [comment]
Try to put them in "unknown_accessories" and disable them there.. i have putted alle my accessories in a "unknown_accessories" seems to work..

**Comment by mifi** [comment]
Yes, the "accessories" property is not used by homebridge-telldus. you should use "unknown_accessories"

**Comment by SubZane** [comment]
Excellent! Thank you!

Maybe this should be added to the documentation, if it's not already there? :)
