### ISSUE TITLE
Things stopped working

### ISSUE THREAD

**Issue by fknorn** [johnlemonse/homebridge-telldus#79]
Hi there,

I know it's sounds weird, but all my devices stopped working recently (red No Response on the HomeKit app). I haven't changed anything on my setup and I tried to debug it as much as possible, but nothing looks out of the ordinary. 

Upon Homebridge startup, it says "Found 12 devices in telldus live." and lists all the devices as they should, Homebridge itself starts just fine and other platforms work, just not anything from Telldus...

Any ideas how I could debug this some more? Thanks!

PS: Homebridge v0.4.50, Node v10.16.3 and homebrdige-telldus version 1.0.7

**Comment by mifi** [comment]
Did u upgrade homebridge or anything else? Or it just Stopped working without doing anything?

**Comment by fknorn** [comment]
Hi, thanks for getting back. No, I don't recall having changed anything. But I did try to update Homebridge and npm, to no avail. How could I best debug this? I don't even know if HomeKit<>Homebridge is the issue or Plugin<>Homebridge or whatever...

**Comment by mifi** [comment]
I think you should just downgrade homebridge for now. I don't really have time or equipment to work on or test this now.
